name: Build
on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
    - name: GitHub Upload Release Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: mei-amt-check_latest
        path: ./mei-amt-check
