name: Build
on:
  workflow_dispatch
jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: GitHub Upload Release Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: mei-amt-check_ubuntu-18.04
        path: ./mei-amt-check
