name: Build
on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, ubuntu-22.04]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
      
    - name: GitHub Upload Release Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: mei-amt-check_latest
        path: ./mei-amt-check
        
    # - name: Release Action
    #   uses: ncipollo/release-action@v1
    #   with:
    #     artifacts: "mei-amt-check"
    #     bodyFile: "body.md"
